# Generated by Django 3.1.6 on 2021-02-23 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backlog_manager', '0002_auto_20210223_1846'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
    ]
