# Generated by Django 3.1.6 on 2021-03-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog_manager', '0005_auto_20210303_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlog',
            name='name',
            field=models.CharField(default='My backlog', max_length=64),
        ),
    ]
